### ISSUE TITLE
Review: Chris P.: s.4.3.2: Consider de-coupling bearer tokens from task config

### ISSUE THREAD

**Issue by cjpatton** [divergentdave/draft-dcook-ppm-dap-interop-test-design#17]
The /internal/test/add_task endpoint calls for a task config with bearer tokens for the leader and, optionally, the collector. Based on https://github.com/divergentdave/draft-dcook-ppm-dap-interop-test-design/issues/7#issuecomment-1273764033, my impression is that the intention is to continue this in the next draft.

I'm fine sticking with bearer tokens, but ultimately I think that implementations of DAP will want to decouple HTTP client auth from the specific task. Towards this goal, I think it would be sensible to de-couple this in the interop draft by specifying separate endpoints for configuring these tokens per-task. For example:

POST /internal/test/set_leader_bearer_token_for_task?task_id=<task_id>
POST /internal/test/set_collector_bearer_token_for_task?task_id=<task_id>

**Comment by cjpatton** [comment]
I'm working this out in Daphne, here's what I would suggest:

```
POST /internal/test/add_authentication_token
```

Schema:
```
{
   "task_id": <bae64url string>
    "role": <either "leader" or "collector">
    "token": <string>
}
```

**Comment by divergentdave** [comment]
I like this idea, I think it makes sense to split the tokens out of `/internal/test/add_task`, as they are no longer part of DAP's conception of task parameters. A separate API for auth tokens also invites configuring future authentication means with their own test APIs, which I think would be easier than continuing to add attributes to the different `add_task` requests. If we want tests to exercise rotation of authentication material down the road, having their configuration split out from immutable task parameters will be helpful.

This leaves the open question of how tasks with zero authentication tokens configured should behave. For now, I'm thinking of leaving the aggregator/collector behavior unspecified (so they can either fail open or fail closed) and requiring that the test runner always provide at least one token before otherwise using a task. This keeps things simple for implementations, and is sufficient to enable happy-path tests. We can revisit this in the future if it needs to be more sophisticated.

**Comment by divergentdave** [comment]
Done in #23.
